version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - pip install -r requirements.txt

  pre_build:
    commands:
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 643426214971.dkr.ecr.ap-south-1.amazonaws.com
      - pytest test_app.py

  build:
    commands:
      - docker build -t mywebapp:latest .

  post_build:
    commands:
      - docker tag mywebapp:latest 643426214971.dkr.ecr.ap-south-1.amazonaws.com/mydevopsproject:latest
      - docker push 643426214971.dkr.ecr.ap-south-1.amazonaws.com/mydevopsproject:latest
